apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
 name: " custom-admission-webhook"
webhooks:
 - name: "custom-admission-webhook"
  #  namespaceSelector:
  #    matchLabels:
  #      admission-webhook: enabled
   rules:
     - apiGroups: [""]
       apiVersions: ["v1"]
       operations: ["CREATE"]
       resources: ["pods"]
       scope: "*"
   admissionReviewVersions: ["v1", "v1beta1"]
   sideEffects: None
   clientConfig:
     service:
       namespace: default
       name: admission-webhook-service
       path: /mutate-pods
       port: 443
     caBundle: afdsfklfkdsfl//#{tobeoverriden-tlscrt}#
    