name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: Webhook
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/aksadmissioncontroller:v1

  aksdeployment:
    runs-on: ubuntu-latest
    steps:     
      - 
        #https://shocksolution.com/2018/12/14/creating-kubernetes-secrets-using-tls-ssl-as-an-example/
        #https://slack.engineering/simple-kubernetes-webhook/
        name: Generate TLS certificate
        shell: bash
        run: |  	
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout tls.key -out tls.crt -subj "/CN=admission-webhook-service.default.svc"
      - uses: azure/k8s-set-context@v2
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
      - uses: actions/checkout@v2
      - 
        #https://shocksolution.com/2018/12/14/creating-kubernetes-secrets-using-tls-ssl-as-an-example/
        #https://slack.engineering/simple-kubernetes-webhook/
        name: deploy secret
        shell: bash
        run: | 
          kubectl create secret tls admission-webhook-TLS-secret --key="tls.key" --cert="tls.crt"
         
      - name: Deploys admission webhook
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: infrastructure/AKSConfig/deployment.yml
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/aksadmissioncontroller:v1
      
      - name: Deploys service
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: infrastructure/AKSConfig/service.yml 

      - name: Deploy mutatingAdmissionWebhookConfiguration
        uses: Azure/k8s-deploy@v3.1
        with:
          action: deploy
          manifests: infrastructure/AKSConfig/mutatingAdmissionWebhookConfiguration.yml 

